### ISSUE TITLE
'supported badges' as tri-state

### ISSUE THREAD

**Issue by raboof** [badgeteam/Hatchery#1]
@annejan is building a 'supported badges' feature, which in its first iteration will likely be boolean: either an app is supported on a given badge, or it is not.

A cool enhancement would be to store this as a tri-state 'supported/unsupported/unknown', though that would likely require an extra db table. Would be nice, but probably best to postpone it until after MVP :smile:.

**Comment by annejan** [comment]
Since it's a many to many relationship, there already is a `badge_project` table, adding a support level there is very do-able . . 

But indeed . . later

**Comment by raboof** [comment]
Ah cool I assumed it was a one (app) to many (badges) relationship for now - then we're indeed closer to that goal than I though. Still, later :smile:

**Comment by annejan** [comment]
New API calls for now ;)
```uri
/basket/[badge]/list/json           - a list of all eggs for specific [badge]
/basket/[badge]/search/json         - [badge] specific search for [words]
/basket/[badge]/category/[cat]/json - json data for category [cat] on [badge]
```

To compliment
```uri
/eggs/get/[app]/json          - get json data for a the egg named [app]
/eggs/list/json               - a list of all eggs with description, revision etc
/eggs/search/[words]/json     - json data for search query [words]
/eggs/categories/json         - json list of categories
/eggs/category/[cat]/json     - json data for category [cat]
```

**Comment by annejan** [comment]
In future the baskets would only hold fully supported eggs :)

**Comment by annejan** [comment]
I have taken the status from the Project status . .  and moved to badge_project . . 

* working
* in_progress
* broken
* unknown

Future idea:
The first two will come in normal API calls . . 
The later two will need a flag . .

**Comment by annejan** [comment]
![Screenshot 2019-09-19 at 16 29 04](https://user-images.githubusercontent.com/294470/65253247-9d76d280-dafa-11e9-80a9-6dc4d740bdd3.png)

**Comment by annejan** [comment]
For filtering, please open a new request . .
