### ISSUE TITLE
git integration

### ISSUE THREAD

**Issue by doebi** [badgeteam/Hatchery#10]
It would be awesome, to have some kind of integration to existing git repositories. With the power of modern CI-Tools we could implement a setup, which updates and publishes hatchery based on "git push".

A possible way of doing this is providing a webhook for each app, that once triggered pulls latest content and publishes. This would require the configuration of branch, url and read permissions to a remote git repo by the user. Which can be done manually or via Github/Gitlab Apps.

**Comment by raboof** [comment]
I agree this would be great. It seems like this could be implemented completely outside of the hatchery, using the hatchery API's to push updates as needed, right?

**Comment by doebi** [comment]
Yeah it could. But it would be much cleaner to have implemented inside, i guess.

The current API allows to update files based on their id (globally unique) so in order to update you have to get all files of a project, update and or create files, and finally publish a new revision.

This is a lot of separate API requests.

**Comment by raboof** [comment]
> it would be much cleaner to have implemented inside

It depends: it also adds a lot of complexity to the hatchery, so in that sense it might actually be 'much cleaner' to have it outside ;)

> The current API allows to update files based on their id (globally unique) so in order to update you have to get all files of a project, update and or create files, and finally publish a new revision

Valid point, it might make sense to add an endpoint to update many files in one request?

**Comment by annejan** [comment]
Deploying external code as a version on hatchery perhaps with webhook functions seems to be the most sane way I can currently think of.

**Comment by annejan** [comment]
Enter: URI + Share Deploy key (SSH pub)
Webhook for updates:

**Comment by annejan** [comment]
![Screenshot 2020-02-24 at 10 17 43](https://user-images.githubusercontent.com/294470/75141869-2a4d3a00-56f2-11ea-9ba0-ba2d0568c3b3.png)
![Screenshot 2020-02-24 at 10 30 54](https://user-images.githubusercontent.com/294470/75141873-2c16fd80-56f2-11ea-8204-46f95f977aa0.png)
![Screenshot 2020-02-24 at 10 40 54](https://user-images.githubusercontent.com/294470/75141881-2de0c100-56f2-11ea-9daa-88ac521ed87f.png)
There are no edit options for files . . . Only update
![Screenshot 2020-02-24 at 10 41 28](https://user-images.githubusercontent.com/294470/75141962-5963ab80-56f2-11ea-85f9-d8fd9d7c807d.png)
![Screenshot 2020-02-24 at 10 40 33](https://user-images.githubusercontent.com/294470/75141970-5bc60580-56f2-11ea-8012-b9be84690ff4.png)

**Comment by annejan** [comment]
This is currently being tested . . and probably incredibly unsafe in current (non-separate worker) version.

**Comment by annejan** [comment]
Discussion point . .

Doe we want to filter which files get imported?
