### ISSUE TITLE
Feature request: license and changes by badgeteam members

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/Hatchery#103]
I'd like apps to have a license field that contains an spdx license identifier style license name. Besides all the standard open source licenses consider adding an option for "other, specified in the readme" and "proprietary" situations. In those last two cases consider adding a note shown to the app author which states something along the lines of "I allow badgeteam to distribute my app" in legal speak 😛 

Additionally a checkbox "I allow Badgeteam members to modify and publish my app to fix problems and to maintain compatibility with future firmware releases", maybe even have it checked by default for new apps.

**Comment by annejan** [comment]
[ ] Backend
[ ] Frontend
