### ISSUE TITLE
readme.md as description

### ISSUE THREAD

**Issue by doebi** [badgeteam/Hatchery#11]
Once #10 is implemented we should parse and render readme.md as html instead of the current description. This allows people to add way more and well-formatted information about their apps.

**Comment by raboof** [comment]
I like this.

We could do this either at the write side ("when a readme.md is updated, also update the description with its contents") or at the read side ("if a readme.md is available, render it, otherwise show the description from the db").

**Comment by doebi** [comment]
To be honest, i would just merge all current descriptions into readme.md. Markdown parsers are backwards compatible to plaintext, so no loss there.

Once merged you only have to deal with one thing, rather than managing two descriptions for all future.

**Comment by annejan** [comment]
I agree that a migration script would probably be best solution . . 

Mostly since files are not really files in Hatchery (except for the tar.gz's)

**Comment by annejan** [comment]
https://badge.team/projects/md_reader :-)

Also when creating an app you get some help . .
![Screenshot 2019-09-06 at 17 46 46](https://user-images.githubusercontent.com/294470/64441522-5803df80-d0ce-11e9-8449-8b0a6f16250e.png)
