### ISSUE TITLE
app name is unique

### ISSUE THREAD

**Issue by doebi** [badgeteam/Hatchery#12]
Currently the name of an app is a unique key. This is somehow understandable from a technical perspective, but it's been used to generally. Sooner or later it's impossible to find meaningful and free app names.

One solution would be to introduce some kind of appkey (unique) and have the name be free.
For eample my weather app could become:
key: at.doebi.weather name: weather

Another would be to bind app names to users automatically (like github)
Example: doebi/weather

There are many other ways to solve this, by adding some form of unique id.

I am looking forward to hearing your opinion.

**Comment by raboof** [comment]
I like namespacing per user (`doebi/weather`). That'd eventually create a need for 'groups'/'organizations', but that might be ok?

**Comment by doebi** [comment]
I don't see a problem in creating hatchery accounts for groups.

Another issue I forgot to mention. What about badge types? What if I want to create a weather app for sha2017 badge and card10 app.

Of course, we could just leave that up to the user..

**Comment by raboof** [comment]
> I don't see a problem in creating hatchery accounts for groups.

I agree, the only problem is someone would have to build it (eventually) :)

> Of course, we could just leave that up to the user..

That sounds reasonable to me. Ideally you'd have one that works on both :D - though indeed that might be tricky as the cardio is not esp32-based

**Comment by annejan** [comment]
Users can delete and re-create (if they really want)

Admins can rename
