### ISSUE TITLE
Needs 'thumbs up' button

### ISSUE THREAD

**Issue by q3k** [badgeteam/Hatchery#16]
Each project on the Hatchery needs a thumbs up button for people to express that they like the project.

**Comment by annejan** [comment]
<img width="401" alt="Screenshot 2019-09-07 at 17 15 43" src="https://user-images.githubusercontent.com/294470/64476747-3ae51480-d193-11e9-805a-a5c8a6bdbdbf.png">
<img width="916" alt="Screenshot 2019-09-07 at 17 16 06" src="https://user-images.githubusercontent.com/294470/64476744-3ae51480-d193-11e9-8910-a64793d4ece3.png">
<img width="318" alt="Screenshot 2019-09-07 at 17 16 18" src="https://user-images.githubusercontent.com/294470/64476743-3a4c7e00-d193-11e9-906d-0e656dfbb7f3.png">
<img width="378" alt="Screenshot 2019-09-07 at 17 16 57" src="https://user-images.githubusercontent.com/294470/64476775-594b1000-d193-11e9-91d4-322d9b199b6f.png">
