### ISSUE TITLE
Issue reporting

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/Hatchery#19]
Can we have a button to let the badgeteam know an app is broken and/or a virus?

**Comment by annejan** [comment]
A report button that sends a mail to bugs[at]badge.team or something sounds simple.

**Comment by annejan** [comment]
No logging yet . . might be more transparent if we do . .

<img width="426" alt="Screenshot 2019-09-18 at 15 13 14" src="https://user-images.githubusercontent.com/294470/65152130-a34fb380-da27-11e9-976d-b96d83633637.png">

Also needs a more professional mail template ;)

**Comment by annejan** [comment]
<img width="411" alt="Screenshot 2019-09-19 at 00 26 41" src="https://user-images.githubusercontent.com/294470/65191422-30b8f500-da74-11e9-86a8-eb7bbb1342f5.png">
