### ISSUE TITLE
Filter API result by badge and category

### ISSUE THREAD

**Issue by nichtich** [badgeteam/Hatchery#20]
The API only supports search and list over all badges. Please add filtering by badge and category like in the web interface, e.g.:

https://badge.team/eggs/list/json?badge=card10&category=wearable

**Comment by annejan** [comment]
The listing is there: https://badge.team/basket/card10/category/wearable/json

For more (interactive) API documentation: https://badge.team/api

Searching with filtering on both will also be added . . 
The whole hatchery system is currently undergoing major updates :)
