### ISSUE TITLE
Amount of eggs in category incorrect when fetching for a specific badge type

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/Hatchery#21]
It is not possible to select a badge type when fetching categories, the amount of eggs is the total amount, not the actually available amount.

**Comment by annejan** [comment]
https://badge.team/basket/sha2017/category/utility/json 48 items
https://badge.team/basket/campzone2019/category/utility/json 9 items

**Comment by annejan** [comment]
For playing with API you can try the new https://badge.team/api

**Comment by annejan** [comment]
Ahhh wait . . I get it . . 

NEW API added
https://badge.team/basket/sha2017/categories/json
https://badge.team/basket/campzone2019/categories/json
