### ISSUE TITLE
Feature request: Uploading BMP's

### ISSUE THREAD

**Issue by royrobotiks** [badgeteam/Hatchery#24]
I just had an issue with uploading 'Gravitris' to the Hatchery: The app requires .BMP files for displaying graphics. Unfortunately, it's only possible to upload png images. My workaround was to rename the images as .txt and the users have to rename them back after download to .bmp. Would be cool, though, if other file types could be uploaded as well.

**Comment by annejan** [comment]
This has been added in secrecy in 8fbb1438db867b17128a431c0a93f95f484b37e0 and updated in 028dc02a5afdbf3fe7a819b48644fbc5542476a8

**Comment by royrobotiks** [comment]
Thanks!
