### ISSUE TITLE
Feature request: Sort by date / latest release

### ISSUE THREAD

**Issue by royrobotiks** [badgeteam/Hatchery#25]
It would be nice to be able to be able to find out quickly which eggs are new in the hatchery.

**Comment by annejan** [comment]
I'm thinking of adding sorting to the frontpage . . 

Will think about it a bit more and probably implement something flexible this week.

**Comment by royrobotiks** [comment]
Super :)

**Comment by annejan** [comment]
https://badge.team/?order=published_at&direction=desc

Changeable by clicking links in the table header ;)
