### ISSUE TITLE
oauth support

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/Hatchery#35]
Please add oauth support so that people can log in into the hatchery with for example their github account

**Comment by annejan** [comment]
That's not entirely how this works . . 

Most systems (like github) require us to register an "app" with them . . 

I can add Github . . Facebook .. Google . . what else @renzenicolai ?

**Comment by renzenicolai** [comment]
Just github :-)

**Comment by annejan** [comment]
![image](https://user-images.githubusercontent.com/294470/100427520-ddd4c780-3092-11eb-9ce8-3339340a6419.png)
Moved to HatcheryNG
![image](https://user-images.githubusercontent.com/294470/100427557-ec22e380-3092-11eb-86a2-454a78ebc244.png)
