### ISSUE TITLE
Hatchery Home Page is Confusing

### ISSUE THREAD

**Issue by LeoDJ** [badgeteam/Hatchery#4]
Currently, there are 404 eggs published in the hatchery (wow).  
Sadly that makes the hatchery home page quite confusing, because the table is neither sorted, nor sortable or filterable.

What would be really helpful in my opinion is to make the table colums sortable and maybe even add filters in the form of drop-down selections for attributes like badge compatibility and category.  
I think that would improve the usability of the hatchery a lot :)

![grafik](https://user-images.githubusercontent.com/5898657/53004489-96d39000-3431-11e9-92e6-8f5c08071575.png)

**Comment by annejan** [comment]
I completely agree and will ask around for someone to design something . . 
Preferable graphic and with some (or all) of the badge on there 😄

**Comment by annejan** [comment]
Now paginated and with badge filtering . .

**Comment by annejan** [comment]
![Screenshot 2020-03-04 at 15 14 23](https://user-images.githubusercontent.com/294470/75887930-d990bc00-5e2a-11ea-83bb-3a1333b31e05.png)

Next plan is to add some static site like on: https://bodge.team/
