### ISSUE TITLE
Add search option or category filtering

### ISSUE THREAD

**Issue by jelly** [badgeteam/Hatchery#8]
There are already many apps in the hatchery and discovering a new app is hard. It would be awesome if you could search for a specific app or filter on a category.

**Comment by annejan** [comment]
![0fc](https://user-images.githubusercontent.com/294470/64417321-245a9280-d099-11e9-8d40-9297b2c757b7.gif)

**Comment by annejan** [comment]
![Screenshot 2019-09-06 at 14 02 28](https://user-images.githubusercontent.com/294470/64426515-00a24700-d0af-11e9-83f3-fa9521b099b2.png)

**Comment by annejan** [comment]
Only 8 cool apps :( https://badge.team/search?search=cool
