### ISSUE TITLE
Specifying Compatibility prevents publishing apps/eggs

### ISSUE THREAD

**Issue by btittelbach** [badgeteam/Hatchery#94]
I've tried to publish my apps/eggs on the hatchery over the last days.

The website displays "... is being published." in a friendly green banner.

Then nothing happens.

**Comment by btittelbach** [comment]
Problem still persists.

I still can't publish neither https://hatchery.badge.team/projects/sensorcommunityluftdatendisplay nor  https://hatchery.badge.team/projects/fontutil

I don't have any errors in the Browser Developer Console, so I've no clue what further help I could provide.

**Comment by annejan** [comment]
Should be fixed in both versions
